# Generated by Django 4.1.5 on 2023-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='events/static')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('organiser', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
