# Generated by Django 4.1.5 on 2023-01-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='events/static')),
                ('organiser', models.CharField(max_length=100)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('number_of_booked_seats', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
