# Generated by Django 4.1.5 on 2023-01-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='number_of_booked_seats',
            new_name='booked_seats',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='number_of_seats',
            new_name='seats',
        ),
    ]
